Bkstg\CoreBundle\Entity\Production:
    type: entity
    repositoryClass: Bkstg\CoreBundle\Repository\ProductionRepository

    indexes:
        slug_index:
            columns: [ slug ]

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
        description:
            type: text
            nullable: true
        status:
            type: boolean
        expiry:
            type: datetime
            nullable: true
        visibility:
            type: string
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        slug:
            type: string
            unique: true
            gedmo:
                slug:
                    handlers:
                        Bkstg\CoreBundle\Doctrine\Handler\BlacklistSluggableHandler:
                            blacklist:
                                - admin
                                - profile
                                - logout
                                - login
                                - resetting
                    fields:
                        - name
        author:
            type: string

    oneToOne:
        image:
            targetEntity: Bkstg\MediaBundle\Entity\Media
            cascade:
                - persist
                - remove
