Bkstg\CoreBundle\Entity\Profile:
    type: entity
    repositoryClass: Bkstg\CoreBundle\Repository\ProfileRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        first_name:
            type: string
            nullable: true
        last_name:
            type: string
            nullable: true
        email:
            type: string
            nullable: true
        height:
            type: length
            nullable: true
        weight:
            type: mass
            nullable: true
        phone:
            type: string
            nullable: true
        facebook:
            type: string
            nullable: true
        twitter:
            type: string
            nullable: true
        slug:
            type: string
            gedmo:
                slug:
                    fields:
                        - first_name
                        - last_name

    oneToOne:
        image:
            targetEntity: Bkstg\MediaBundle\Entity\Media
            cascade:
                - persist
                - remove

    manyToMany:
        group:
            targetEntity: Bkstg\CoreBundle\Entity\Production

    manyToOne:
        author:
            targetEntity: Bkstg\CoreBundle\Entity\User
            inversedBy: profiles
