Bkstg\CoreBundle\Entity\User:
    type: entity
    repositoryClass: Bkstg\CoreBundle\Repository\UserRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    oneToMany:
        memberships:
            targetEntity: Bkstg\CoreBundle\Entity\ProductionMembership
            mappedBy: member
        profiles:
            targetEntity: Bkstg\CoreBundle\Entity\Profile
            mappedBy: author

