services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Bkstg\CoreBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests,Search}'

    # Controller services.
    Bkstg\CoreBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags:
            - { name: controller.service_arguments }
    Bkstg\CoreBundle\Controller\MediaController:
        public: true
        tags:
            - { name: controller.service_arguments }
        arguments:
            - '@sonata.media.pool'

    # Menu matcher service.
    Bkstg\CoreBundle\Menu\Matcher\PathAncestorMatcher:
        public: true
        arguments:
            - []

    # Menu builders.
    Bkstg\CoreBundle\Menu\MenuBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: createAdminMenu, alias: bkstg_admin_menu }
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: bkstg_main_menu }
            - { name: knp_menu.menu_builder, method: createProductionMenu, alias: bkstg_production_menu }
            - { name: knp_menu.menu_builder, method: createUserMenu, alias: bkstg_user_menu }

    # Doctrine event listener services.
    Bkstg\CoreBundle\EventListener\PublishableListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
            - { name: doctrine.event_listener, event: postPersist, lazy: true }
            - { name: doctrine.event_listener, event: preUpdate, lazy: true }
            - { name: doctrine.event_listener, event: postUpdate, lazy: true }
    bkstg.core.cdn.private_do_spaces:
        class: Bkstg\CoreBundle\CDN\PrivateDigitalOceanSpaces
        arguments: [null, null]
    bkstg.core.adapter.service.do_spaces:
        class: Aws\S3\S3Client
        factory: ['Aws\S3\S3Client', factory]
        arguments: [null]
    bkstg.core.adapter.filesystem.do_spaces:
        class: Gaufrette\Adapter\AwsS3
        arguments: [null, null, null]
    bkstg.core.filesystem.do_spaces:
        class: Gaufrette\Filesystem
        arguments:
            - '@bkstg.core.adapter.filesystem.do_spaces'
