services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Bkstg\CoreBundle\:
        resource: '../../*'
        exclude: '../../{Model,Repository,Tests}'
    Bkstg\CoreBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags:
            - { name: controller.service_arguments }

    # Menu services.
    Bkstg\CoreBundle\Menu\NavbarMenuRenderer:
        public: true
        tags:
            - { name: knp_menu.renderer, alias: bkstg_menu_navbar_renderer }
    Bkstg\CoreBundle\Menu\MenuRequestUriVoter:
        public: true
        tags:
            - { name: knp_menu.voter }
    Bkstg\CoreBundle\Menu\MainMenuBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: bkstg_main_menu }

    # Register contrib services.
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
