services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Bkstg\CoreBundle\:
        resource: '../../*'
        exclude: '../../{Model,Repository,Tests}'

    # Controller services.
    Bkstg\CoreBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags:
            - { name: controller.service_arguments }

    # Block services.
    Bkstg\CoreBundle\Block\:
        resource: '../../Block'
        public: true
        arguments:
            - null
        tags:
            - { name: sonata.block }

    # Menu services.
    Bkstg\CoreBundle\Menu\Voter\:
        resource: '../../Menu/Voter'
        public: true
        tags:
            - { name: knp_menu.voter }
    Bkstg\CoreBundle\Menu\MenuBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: createAdminMenu, alias: bkstg_admin_menu }
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: bkstg_main_menu }
            - { name: knp_menu.menu_builder, method: createProductionMenu, alias: bkstg_production_menu }

    # Register contrib services.
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }
    Gedmo\Timestampable\TimestampableListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
    Gedmo\Sluggable\SluggableListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
