services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Bkstg\CoreBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    # Controller services.
    Bkstg\CoreBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags:
            - { name: controller.service_arguments }

    # Menu matcher service.
    Bkstg\CoreBundle\Menu\Matcher\PathAncestorMatcher:
        public: true
        arguments:
            - []

    # Menu builders.
    Bkstg\CoreBundle\Menu\MenuBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: createAdminMenu, alias: bkstg_admin_menu }
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: bkstg_main_menu }
            - { name: knp_menu.menu_builder, method: createProductionMenu, alias: bkstg_production_menu }
            - { name: knp_menu.menu_builder, method: createUserMenu, alias: bkstg_user_menu }

    # Doctrine event listener services.
    Bkstg\CoreBundle\EventListener\PublishableListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
            - { name: doctrine.event_listener, event: preUpdate, lazy: true }
