stages:
    - test

# Cache the installation of composer deps.
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - vendor/
before_script:
    - composer install --no-progress --no-interaction --ignore-platform-reqs
variables:
    COMPOSER_MEMORY_LIMIT: -1

# Test coding standards.
coding standards:
    image: registry.gitlab.com/forestcitylabs/ops/phpcs:latest
    stage: test
    script:
        - phpcs .

# Run unit tests.
unit tests:
    image: registry.gitlab.com/forestcitylabs/ops/phpunit:latest
    stage: test
    script:
        - phpunit --colors=never --coverage-text
