language: php

php:
    - 7.1
    - 7.2
    - 7.3

env:
    - COMPOSER_MEMORY_LIMIT=-1

before_script:
    - composer install --no-interaction --no-scripts --no-progress

script:
    - ./vendor/bin/phpcs .
    - ./vendor/bin/phpunit
