Bkstg\CoreBundle\Model\ProductionMembership:
    type: entity
    repositoryClass: Bkstg\CoreBundle\Repository\ProductionMembershipRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        status:
            type: smallint
        roles:
            type: array
        expiry:
            type: datetime
            nullable: true

    manyToOne:
        member:
            targetEntity: Bkstg\CoreBundle\Model\User
            inversedBy: memberships
        group:
            targetEntity: Bkstg\CoreBundle\Model\Production
            inversedBy: memberships
