<?php

namespace Bkstg\CoreBundle\Repository;

use Bkstg\CoreBundle\Entity\Production;
use Bkstg\CoreBundle\Entity\User;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityRepository;

/**
 * ProductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionRepository extends EntityRepository
{
    /**
     * Finds *all* open productions.
     *
     * These results are not filtered and, therefore, should only be available
     * to administrators.
     *
     * @return Production[]
     */
    public function findAllOpen()
    {
        // Build criteria.
        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('status', Production::STATUS_ACTIVE))
            ->andWhere(
                Criteria::expr()->orX(
                    Criteria::expr()->isNull('expiry'),
                    Criteria::expr()->gt('expiry', new \DateTime())
                )
            );
        return $this->matching($criteria);
    }

    /**
     * Finds *all* closed productions.
     *
     * These results are not filtered and, therefore, should only be available
     * to administrators.
     *
     * @return Production[]
     */
    public function findAllClosed()
    {
        // Build criteria.
        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('status', Production::STATUS_CLOSED))
            ->orWhere(Criteria::expr()->lte('expiry', new \DateTime()));
        return $this->matching($criteria);
    }
}
