<?php

namespace Bkstg\CoreBundle\Repository;

/**
 * ProductionMembershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionMembershipRepository extends \Doctrine\ORM\EntityRepository
{
}
