<?php

namespace Bkstg\CoreBundle\Repository;

/**
 * ProductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionRepository extends \Doctrine\ORM\EntityRepository
{
}
