<?php

namespace Bkstg\CoreBundle\Repository;

use Bkstg\CoreBundle\Model\Group\GroupMembershipInterface;
use Bkstg\CoreBundle\Model\User;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityRepository;

/**
 * ProductionMembershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionMembershipRepository extends EntityRepository
{
    public function findActiveMemberships(User $user)
    {
        // Build criteria.
        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('status', GroupMembershipInterface::STATUS_ACTIVE))
            ->andWhere(Criteria::expr()->eq('member', $user))
            ->andWhere(
                Criteria::expr()->orX(
                    Criteria::expr()->isNull('expiry'),
                    Criteria::expr()->gt('expiry', new \DateTime())
                )
            );
        return $this->matching($criteria);
    }
}
