<?php

namespace Bkstg\CoreBundle\Repository;

use Bkstg\CoreBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{
    public function findGlobalProfile(User $user)
    {
        $qb = $this->createQueryBuilder('p');
        return $qb
            ->leftJoin('p.group', 'g')
            ->andWhere($qb->expr()->eq('p.author', ':author'))
            ->andWhere($qb->expr()->isNull('g.id'))
            ->setParameter('author', $user)
            ->getQuery()
            ->getSingleResult();
    }
}
