<?php

namespace Bkstg\CoreBundle\Repository;

use Bkstg\CoreBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{
    public function findGlobalProfile(UserInterface $user)
    {
        $profile = null;

        // Get a query builder and build a query.
        $qb = $this->createQueryBuilder('p');
        $query = $qb
            ->leftJoin('p.group', 'g')
            ->andWhere($qb->expr()->eq('p.author', ':author'))
            ->andWhere($qb->expr()->isNull('g.id'))
            ->setParameter('author', $user->getUsername())
            ->getQuery();

        try {
            $profile = $query->getSingleResult();
        } catch (NoResultException $e) {
            // Nothing to be concerned about.
        }

        return $profile;
    }
}
