bkstg_admin_redirect:
    path: /
    methods: [GET]
    defaults:
        _controller: Bkstg\CoreBundle\Controller\AdminController:redirectAction
bkstg_admin_dashboard:
    path: /dashboard
    methods: [GET]
    defaults:
        _controller: Bkstg\CoreBundle\Controller\AdminController:dashboardAction
