bkstg_admin_redirect:
    path: /
    defaults:
        _controller: Bkstg\CoreBundle\Controller\AdminController:redirectAction
bkstg_admin_dashboard:
    path: /dashboard
    defaults:
        _controller: Bkstg\CoreBundle\Controller\AdminController:dashboardAction
