bkstg_admin:
    resource: '@BkstgCoreBundle/Resources/config/routing/admin.yml'
bkstg_profile:
    resource: '@BkstgCoreBundle/Resources/config/routing/profile.yml'
bkstg_membership:
    resource: '@BkstgCoreBundle/Resources/config/routing/membership.yml'
bkstg_production:
    resource: '@BkstgCoreBundle/Resources/config/routing/production.yml'
