bkstg_admin:
    resource: '@BkstgCoreBundle/Resources/config/routing/admin.yml'
bkstg_production_admin:
    prefix: /admin/productions
    resource: '@BkstgCoreBundle/Resources/config/routing/production_admin.yml'
bkstg_production_settings:
    resource: '@BkstgCoreBundle/Resources/config/routing/production_settings.yml'
bkstg_production:
    resource: '@BkstgCoreBundle/Resources/config/routing/production.yml'
