bkstg_membership_list:
    path: /{production_slug}/members
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProductionMembershipController:indexAction
bkstg_membership_create:
    path: /{production_slug}/members/add
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProductionMembershipController:createAction
bkstg_membership_edit:
    path: /{production_slug}/members/{id}/edit
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProductionMembershipController:updateAction
bkstg_membership_delete:
    path: /{production_slug}/members/{id}/delete
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProductionMembershipController:deleteAction
