bkstg_production_read:
    path: /{production_slug}
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProductionController:readAction
bkstg_production_overview:
    path: /{production_slug}/overview
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProductionController:overviewAction
bkstg_production_settings:
    path: /{production_slug}/settings/
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProductionController:settingsAction
