bkstg_production_admin_index:
    path: /
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProductionAdminController:indexAction
bkstg_production_admin_archive:
    path: /archive
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProductionAdminController:archiveAction
bkstg_production_admin_create:
    path: /create
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProductionAdminController:createAction
bkstg_production_admin_update:
    path: /{id}/edit
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProductionAdminController:updateAction
bkstg_production_admin_delete:
    path: /{id}/delete
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProductionAdminController:deleteAction
