bkstg_production_show:
    path: /{production_slug}
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProductionController:readAction
bkstg_production_overview:
    path: /{production_slug}/overview
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProductionController:overviewAction
