bkstg_production_read:
    path: /
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProductionController:readAction
bkstg_production_overview:
    path: /overview
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProductionController:overviewAction
bkstg_production_settings:
    path: /settings
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProductionController:settingsAction
