bkstg_profile_redirect:
    path: /profile
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProfileController:redirectAction
bkstg_profile_list:
    path: /directory
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProfileController:indexAction
bkstg_profile_create:
    path: /profile/create
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProfileController:createAction
bkstg_profile_show:
    path: /profile/{profile_slug}
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProfileController:readAction
bkstg_profile_edit:
    path: /profile/{id}/edit
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProfileController:updateAction
bkstg_profile_delete:
    path: /profile/{id}/delete
    defaults:
        _controller: Bkstg\CoreBundle\Controller\ProfileController:deleteAction
