bkstg_user_list:
    path: /admin/users
    defaults:
        _controller: Bkstg\CoreBundle\Controller\UserController:indexAction
bkstg_user_create:
    path: /admin/users/create
    defaults:
        _controller: Bkstg\CoreBundle\Controller\UserController:createAction
bkstg_user_show:
    path: /admin/users/{id}
    defaults:
        _controller: Bkstg\CoreBundle\Controller\UserController:readAction
bkstg_user_edit:
    path: /admin/users/{id}/edit
    defaults:
        _controller: Bkstg\CoreBundle\Controller\UserController:updateAction
bkstg_user_delete:
    path: /admin/users/{id}/delete
    defaults:
        _controller: Bkstg\CoreBundle\Controller\UserController:deleteAction
